// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Auth.proto

package com.bce.dts.protobuf;

public final class AuthOuterClass {
  private AuthOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AuthOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.bce.dts.protobuf.Auth)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 消息类型
     * </pre>
     *
     * <code>.com.bce.dts.protobuf.MsgType type = 1;</code>
     */
    int getTypeValue();
    /**
     * <pre>
     * 消息类型
     * </pre>
     *
     * <code>.com.bce.dts.protobuf.MsgType type = 1;</code>
     */
    com.bce.dts.protobuf.Common.MsgType getType();

    /**
     * <pre>
     * api server的host
     * </pre>
     *
     * <code>string host = 2;</code>
     */
    java.lang.String getHost();
    /**
     * <pre>
     * api server的host
     * </pre>
     *
     * <code>string host = 2;</code>
     */
    com.google.protobuf.ByteString
        getHostBytes();

    /**
     * <pre>
     * utc time
     * </pre>
     *
     * <code>string bce_date = 3;</code>
     */
    java.lang.String getBceDate();
    /**
     * <pre>
     * utc time
     * </pre>
     *
     * <code>string bce_date = 3;</code>
     */
    com.google.protobuf.ByteString
        getBceDateBytes();

    /**
     * <pre>
     * 生成的签名
     * </pre>
     *
     * <code>string authorization = 4;</code>
     */
    java.lang.String getAuthorization();
    /**
     * <pre>
     * 生成的签名
     * </pre>
     *
     * <code>string authorization = 4;</code>
     */
    com.google.protobuf.ByteString
        getAuthorizationBytes();

    /**
     * <pre>
     * 鉴权的api url
     * </pre>
     *
     * <code>string path = 5;</code>
     */
    java.lang.String getPath();
    /**
     * <pre>
     * 鉴权的api url
     * </pre>
     *
     * <code>string path = 5;</code>
     */
    com.google.protobuf.ByteString
        getPathBytes();

    /**
     * <pre>
     * dts任务id
     * </pre>
     *
     * <code>string dts_id = 6;</code>
     */
    java.lang.String getDtsId();
    /**
     * <pre>
     * dts任务id
     * </pre>
     *
     * <code>string dts_id = 6;</code>
     */
    com.google.protobuf.ByteString
        getDtsIdBytes();
  }
  /**
   * Protobuf type {@code com.bce.dts.protobuf.Auth}
   */
  public  static final class Auth extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.bce.dts.protobuf.Auth)
      AuthOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Auth.newBuilder() to construct.
    private Auth(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Auth() {
      type_ = 0;
      host_ = "";
      bceDate_ = "";
      authorization_ = "";
      path_ = "";
      dtsId_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Auth(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              host_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              bceDate_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              authorization_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              path_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              dtsId_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bce.dts.protobuf.AuthOuterClass.internal_static_baidu_river_Auth_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bce.dts.protobuf.AuthOuterClass.internal_static_baidu_river_Auth_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bce.dts.protobuf.AuthOuterClass.Auth.class, com.bce.dts.protobuf.AuthOuterClass.Auth.Builder.class);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <pre>
     * 消息类型
     * </pre>
     *
     * <code>.com.bce.dts.protobuf.MsgType type = 1;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <pre>
     * 消息类型
     * </pre>
     *
     * <code>.com.bce.dts.protobuf.MsgType type = 1;</code>
     */
    public com.bce.dts.protobuf.Common.MsgType getType() {
      com.bce.dts.protobuf.Common.MsgType result = com.bce.dts.protobuf.Common.MsgType.valueOf(type_);
      return result == null ? com.bce.dts.protobuf.Common.MsgType.UNRECOGNIZED : result;
    }

    public static final int HOST_FIELD_NUMBER = 2;
    private volatile java.lang.Object host_;
    /**
     * <pre>
     * api server的host
     * </pre>
     *
     * <code>string host = 2;</code>
     */
    public java.lang.String getHost() {
      java.lang.Object ref = host_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        host_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * api server的host
     * </pre>
     *
     * <code>string host = 2;</code>
     */
    public com.google.protobuf.ByteString
        getHostBytes() {
      java.lang.Object ref = host_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        host_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BCE_DATE_FIELD_NUMBER = 3;
    private volatile java.lang.Object bceDate_;
    /**
     * <pre>
     * utc time
     * </pre>
     *
     * <code>string bce_date = 3;</code>
     */
    public java.lang.String getBceDate() {
      java.lang.Object ref = bceDate_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        bceDate_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * utc time
     * </pre>
     *
     * <code>string bce_date = 3;</code>
     */
    public com.google.protobuf.ByteString
        getBceDateBytes() {
      java.lang.Object ref = bceDate_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bceDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AUTHORIZATION_FIELD_NUMBER = 4;
    private volatile java.lang.Object authorization_;
    /**
     * <pre>
     * 生成的签名
     * </pre>
     *
     * <code>string authorization = 4;</code>
     */
    public java.lang.String getAuthorization() {
      java.lang.Object ref = authorization_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        authorization_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 生成的签名
     * </pre>
     *
     * <code>string authorization = 4;</code>
     */
    public com.google.protobuf.ByteString
        getAuthorizationBytes() {
      java.lang.Object ref = authorization_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        authorization_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PATH_FIELD_NUMBER = 5;
    private volatile java.lang.Object path_;
    /**
     * <pre>
     * 鉴权的api url
     * </pre>
     *
     * <code>string path = 5;</code>
     */
    public java.lang.String getPath() {
      java.lang.Object ref = path_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        path_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 鉴权的api url
     * </pre>
     *
     * <code>string path = 5;</code>
     */
    public com.google.protobuf.ByteString
        getPathBytes() {
      java.lang.Object ref = path_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        path_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DTS_ID_FIELD_NUMBER = 6;
    private volatile java.lang.Object dtsId_;
    /**
     * <pre>
     * dts任务id
     * </pre>
     *
     * <code>string dts_id = 6;</code>
     */
    public java.lang.String getDtsId() {
      java.lang.Object ref = dtsId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dtsId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * dts任务id
     * </pre>
     *
     * <code>string dts_id = 6;</code>
     */
    public com.google.protobuf.ByteString
        getDtsIdBytes() {
      java.lang.Object ref = dtsId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dtsId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != com.bce.dts.protobuf.Common.MsgType.UNKNOW.getNumber()) {
        output.writeEnum(1, type_);
      }
      if (!getHostBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, host_);
      }
      if (!getBceDateBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, bceDate_);
      }
      if (!getAuthorizationBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, authorization_);
      }
      if (!getPathBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, path_);
      }
      if (!getDtsIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, dtsId_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != com.bce.dts.protobuf.Common.MsgType.UNKNOW.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (!getHostBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, host_);
      }
      if (!getBceDateBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, bceDate_);
      }
      if (!getAuthorizationBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, authorization_);
      }
      if (!getPathBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, path_);
      }
      if (!getDtsIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, dtsId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.bce.dts.protobuf.AuthOuterClass.Auth)) {
        return super.equals(obj);
      }
      com.bce.dts.protobuf.AuthOuterClass.Auth other = (com.bce.dts.protobuf.AuthOuterClass.Auth) obj;

      boolean result = true;
      result = result && type_ == other.type_;
      result = result && getHost()
          .equals(other.getHost());
      result = result && getBceDate()
          .equals(other.getBceDate());
      result = result && getAuthorization()
          .equals(other.getAuthorization());
      result = result && getPath()
          .equals(other.getPath());
      result = result && getDtsId()
          .equals(other.getDtsId());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + HOST_FIELD_NUMBER;
      hash = (53 * hash) + getHost().hashCode();
      hash = (37 * hash) + BCE_DATE_FIELD_NUMBER;
      hash = (53 * hash) + getBceDate().hashCode();
      hash = (37 * hash) + AUTHORIZATION_FIELD_NUMBER;
      hash = (53 * hash) + getAuthorization().hashCode();
      hash = (37 * hash) + PATH_FIELD_NUMBER;
      hash = (53 * hash) + getPath().hashCode();
      hash = (37 * hash) + DTS_ID_FIELD_NUMBER;
      hash = (53 * hash) + getDtsId().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.bce.dts.protobuf.AuthOuterClass.Auth parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bce.dts.protobuf.AuthOuterClass.Auth parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bce.dts.protobuf.AuthOuterClass.Auth parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bce.dts.protobuf.AuthOuterClass.Auth parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bce.dts.protobuf.AuthOuterClass.Auth parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bce.dts.protobuf.AuthOuterClass.Auth parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bce.dts.protobuf.AuthOuterClass.Auth parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bce.dts.protobuf.AuthOuterClass.Auth parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bce.dts.protobuf.AuthOuterClass.Auth parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.bce.dts.protobuf.AuthOuterClass.Auth parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bce.dts.protobuf.AuthOuterClass.Auth parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bce.dts.protobuf.AuthOuterClass.Auth parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.bce.dts.protobuf.AuthOuterClass.Auth prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.bce.dts.protobuf.Auth}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.bce.dts.protobuf.Auth)
        com.bce.dts.protobuf.AuthOuterClass.AuthOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.bce.dts.protobuf.AuthOuterClass.internal_static_baidu_river_Auth_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.bce.dts.protobuf.AuthOuterClass.internal_static_baidu_river_Auth_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.bce.dts.protobuf.AuthOuterClass.Auth.class, com.bce.dts.protobuf.AuthOuterClass.Auth.Builder.class);
      }

      // Construct using com.bce.dts.protobuf.AuthOuterClass.Auth.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        type_ = 0;

        host_ = "";

        bceDate_ = "";

        authorization_ = "";

        path_ = "";

        dtsId_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bce.dts.protobuf.AuthOuterClass.internal_static_baidu_river_Auth_descriptor;
      }

      public com.bce.dts.protobuf.AuthOuterClass.Auth getDefaultInstanceForType() {
        return com.bce.dts.protobuf.AuthOuterClass.Auth.getDefaultInstance();
      }

      public com.bce.dts.protobuf.AuthOuterClass.Auth build() {
        com.bce.dts.protobuf.AuthOuterClass.Auth result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.bce.dts.protobuf.AuthOuterClass.Auth buildPartial() {
        com.bce.dts.protobuf.AuthOuterClass.Auth result = new com.bce.dts.protobuf.AuthOuterClass.Auth(this);
        result.type_ = type_;
        result.host_ = host_;
        result.bceDate_ = bceDate_;
        result.authorization_ = authorization_;
        result.path_ = path_;
        result.dtsId_ = dtsId_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bce.dts.protobuf.AuthOuterClass.Auth) {
          return mergeFrom((com.bce.dts.protobuf.AuthOuterClass.Auth)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.bce.dts.protobuf.AuthOuterClass.Auth other) {
        if (other == com.bce.dts.protobuf.AuthOuterClass.Auth.getDefaultInstance()) return this;
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (!other.getHost().isEmpty()) {
          host_ = other.host_;
          onChanged();
        }
        if (!other.getBceDate().isEmpty()) {
          bceDate_ = other.bceDate_;
          onChanged();
        }
        if (!other.getAuthorization().isEmpty()) {
          authorization_ = other.authorization_;
          onChanged();
        }
        if (!other.getPath().isEmpty()) {
          path_ = other.path_;
          onChanged();
        }
        if (!other.getDtsId().isEmpty()) {
          dtsId_ = other.dtsId_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.bce.dts.protobuf.AuthOuterClass.Auth parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.bce.dts.protobuf.AuthOuterClass.Auth) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int type_ = 0;
      /**
       * <pre>
       * 消息类型
       * </pre>
       *
       * <code>.com.bce.dts.protobuf.MsgType type = 1;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <pre>
       * 消息类型
       * </pre>
       *
       * <code>.com.bce.dts.protobuf.MsgType type = 1;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息类型
       * </pre>
       *
       * <code>.com.bce.dts.protobuf.MsgType type = 1;</code>
       */
      public com.bce.dts.protobuf.Common.MsgType getType() {
        com.bce.dts.protobuf.Common.MsgType result = com.bce.dts.protobuf.Common.MsgType.valueOf(type_);
        return result == null ? com.bce.dts.protobuf.Common.MsgType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * 消息类型
       * </pre>
       *
       * <code>.com.bce.dts.protobuf.MsgType type = 1;</code>
       */
      public Builder setType(com.bce.dts.protobuf.Common.MsgType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息类型
       * </pre>
       *
       * <code>.com.bce.dts.protobuf.MsgType type = 1;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object host_ = "";
      /**
       * <pre>
       * api server的host
       * </pre>
       *
       * <code>string host = 2;</code>
       */
      public java.lang.String getHost() {
        java.lang.Object ref = host_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          host_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * api server的host
       * </pre>
       *
       * <code>string host = 2;</code>
       */
      public com.google.protobuf.ByteString
          getHostBytes() {
        java.lang.Object ref = host_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          host_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * api server的host
       * </pre>
       *
       * <code>string host = 2;</code>
       */
      public Builder setHost(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        host_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * api server的host
       * </pre>
       *
       * <code>string host = 2;</code>
       */
      public Builder clearHost() {
        
        host_ = getDefaultInstance().getHost();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * api server的host
       * </pre>
       *
       * <code>string host = 2;</code>
       */
      public Builder setHostBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        host_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object bceDate_ = "";
      /**
       * <pre>
       * utc time
       * </pre>
       *
       * <code>string bce_date = 3;</code>
       */
      public java.lang.String getBceDate() {
        java.lang.Object ref = bceDate_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          bceDate_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * utc time
       * </pre>
       *
       * <code>string bce_date = 3;</code>
       */
      public com.google.protobuf.ByteString
          getBceDateBytes() {
        java.lang.Object ref = bceDate_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          bceDate_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * utc time
       * </pre>
       *
       * <code>string bce_date = 3;</code>
       */
      public Builder setBceDate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        bceDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * utc time
       * </pre>
       *
       * <code>string bce_date = 3;</code>
       */
      public Builder clearBceDate() {
        
        bceDate_ = getDefaultInstance().getBceDate();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * utc time
       * </pre>
       *
       * <code>string bce_date = 3;</code>
       */
      public Builder setBceDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        bceDate_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object authorization_ = "";
      /**
       * <pre>
       * 生成的签名
       * </pre>
       *
       * <code>string authorization = 4;</code>
       */
      public java.lang.String getAuthorization() {
        java.lang.Object ref = authorization_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          authorization_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 生成的签名
       * </pre>
       *
       * <code>string authorization = 4;</code>
       */
      public com.google.protobuf.ByteString
          getAuthorizationBytes() {
        java.lang.Object ref = authorization_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          authorization_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 生成的签名
       * </pre>
       *
       * <code>string authorization = 4;</code>
       */
      public Builder setAuthorization(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        authorization_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 生成的签名
       * </pre>
       *
       * <code>string authorization = 4;</code>
       */
      public Builder clearAuthorization() {
        
        authorization_ = getDefaultInstance().getAuthorization();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 生成的签名
       * </pre>
       *
       * <code>string authorization = 4;</code>
       */
      public Builder setAuthorizationBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        authorization_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object path_ = "";
      /**
       * <pre>
       * 鉴权的api url
       * </pre>
       *
       * <code>string path = 5;</code>
       */
      public java.lang.String getPath() {
        java.lang.Object ref = path_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          path_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 鉴权的api url
       * </pre>
       *
       * <code>string path = 5;</code>
       */
      public com.google.protobuf.ByteString
          getPathBytes() {
        java.lang.Object ref = path_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          path_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 鉴权的api url
       * </pre>
       *
       * <code>string path = 5;</code>
       */
      public Builder setPath(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        path_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 鉴权的api url
       * </pre>
       *
       * <code>string path = 5;</code>
       */
      public Builder clearPath() {
        
        path_ = getDefaultInstance().getPath();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 鉴权的api url
       * </pre>
       *
       * <code>string path = 5;</code>
       */
      public Builder setPathBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        path_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object dtsId_ = "";
      /**
       * <pre>
       * dts任务id
       * </pre>
       *
       * <code>string dts_id = 6;</code>
       */
      public java.lang.String getDtsId() {
        java.lang.Object ref = dtsId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          dtsId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * dts任务id
       * </pre>
       *
       * <code>string dts_id = 6;</code>
       */
      public com.google.protobuf.ByteString
          getDtsIdBytes() {
        java.lang.Object ref = dtsId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dtsId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * dts任务id
       * </pre>
       *
       * <code>string dts_id = 6;</code>
       */
      public Builder setDtsId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        dtsId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * dts任务id
       * </pre>
       *
       * <code>string dts_id = 6;</code>
       */
      public Builder clearDtsId() {
        
        dtsId_ = getDefaultInstance().getDtsId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * dts任务id
       * </pre>
       *
       * <code>string dts_id = 6;</code>
       */
      public Builder setDtsIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        dtsId_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.bce.dts.protobuf.Auth)
    }

    // @@protoc_insertion_point(class_scope:com.bce.dts.protobuf.Auth)
    private static final com.bce.dts.protobuf.AuthOuterClass.Auth DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.bce.dts.protobuf.AuthOuterClass.Auth();
    }

    public static com.bce.dts.protobuf.AuthOuterClass.Auth getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Auth>
        PARSER = new com.google.protobuf.AbstractParser<Auth>() {
      public Auth parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Auth(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Auth> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Auth> getParserForType() {
      return PARSER;
    }

    public com.bce.dts.protobuf.AuthOuterClass.Auth getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_baidu_river_Auth_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_baidu_river_Auth_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nAuth.proto\022\013com.bce.dts.protobuf\032\014Common.proto\"" +
      "\177\n\004Auth\022\"\n\004type\030\001 \001(\0162\024.com.bce.dts.protobuf.MsgT" +
      "ype\022\014\n\004host\030\002 \001(\t\022\020\n\010bce_date\030\003 \001(\t\022\025\n\ra" +
      "uthorization\030\004 \001(\t\022\014\n\004path\030\005 \001(\t\022\016\n\006dts_" +
      "id\030\006 \001(\tb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.bce.dts.protobuf.Common.getDescriptor(),
        }, assigner);
    internal_static_baidu_river_Auth_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_baidu_river_Auth_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_baidu_river_Auth_descriptor,
        new java.lang.String[] { "Type", "Host", "BceDate", "Authorization", "Path", "DtsId", });
    com.bce.dts.protobuf.Common.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
