// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: End.proto

package com.bce.dts.protobuf;

public final class EndOuterClass {
  private EndOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface EndOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.bce.dts.protobuf.End)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 消息类型
     * </pre>
     *
     * <code>.com.bce.dts.protobuf.MsgType type = 1;</code>
     */
    int getTypeValue();
    /**
     * <pre>
     * 消息类型
     * </pre>
     *
     * <code>.com.bce.dts.protobuf.MsgType type = 1;</code>
     */
    com.bce.dts.protobuf.Common.MsgType getType();

    /**
     * <pre>
     * dts任务id
     * </pre>
     *
     * <code>string dts_id = 2;</code>
     */
    java.lang.String getDtsId();
    /**
     * <pre>
     * dts任务id
     * </pre>
     *
     * <code>string dts_id = 2;</code>
     */
    com.google.protobuf.ByteString
        getDtsIdBytes();

    /**
     * <pre>
     * client已消费的kafka offset, 如果是非COMMIT_OFFSET类型的ACK，为空串
     * </pre>
     *
     * <code>string offset = 3;</code>
     */
    java.lang.String getOffset();
    /**
     * <pre>
     * client已消费的kafka offset, 如果是非COMMIT_OFFSET类型的ACK，为空串
     * </pre>
     *
     * <code>string offset = 3;</code>
     */
    com.google.protobuf.ByteString
        getOffsetBytes();

    /**
     * <pre>
     * client消费点的binlog位置
     * </pre>
     *
     * <code>string position = 4;</code>
     */
    java.lang.String getPosition();
    /**
     * <pre>
     * client消费点的binlog位置
     * </pre>
     *
     * <code>string position = 4;</code>
     */
    com.google.protobuf.ByteString
        getPositionBytes();

    /**
     * <pre>
     * 最后一条binlog记录的时间戳
     * </pre>
     *
     * <code>string timestamp = 5;</code>
     */
    java.lang.String getTimestamp();
    /**
     * <pre>
     * 最后一条binlog记录的时间戳
     * </pre>
     *
     * <code>string timestamp = 5;</code>
     */
    com.google.protobuf.ByteString
        getTimestampBytes();
  }
  /**
   * Protobuf type {@code com.bce.dts.protobuf.End}
   */
  public  static final class End extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.bce.dts.protobuf.End)
      EndOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use End.newBuilder() to construct.
    private End(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private End() {
      type_ = 0;
      dtsId_ = "";
      offset_ = "";
      position_ = "";
      timestamp_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private End(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              dtsId_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              offset_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              position_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              timestamp_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bce.dts.protobuf.EndOuterClass.internal_static_baidu_river_End_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bce.dts.protobuf.EndOuterClass.internal_static_baidu_river_End_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bce.dts.protobuf.EndOuterClass.End.class, com.bce.dts.protobuf.EndOuterClass.End.Builder.class);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <pre>
     * 消息类型
     * </pre>
     *
     * <code>.com.bce.dts.protobuf.MsgType type = 1;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <pre>
     * 消息类型
     * </pre>
     *
     * <code>.com.bce.dts.protobuf.MsgType type = 1;</code>
     */
    public com.bce.dts.protobuf.Common.MsgType getType() {
      com.bce.dts.protobuf.Common.MsgType result = com.bce.dts.protobuf.Common.MsgType.valueOf(type_);
      return result == null ? com.bce.dts.protobuf.Common.MsgType.UNRECOGNIZED : result;
    }

    public static final int DTS_ID_FIELD_NUMBER = 2;
    private volatile java.lang.Object dtsId_;
    /**
     * <pre>
     * dts任务id
     * </pre>
     *
     * <code>string dts_id = 2;</code>
     */
    public java.lang.String getDtsId() {
      java.lang.Object ref = dtsId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dtsId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * dts任务id
     * </pre>
     *
     * <code>string dts_id = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDtsIdBytes() {
      java.lang.Object ref = dtsId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dtsId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OFFSET_FIELD_NUMBER = 3;
    private volatile java.lang.Object offset_;
    /**
     * <pre>
     * client已消费的kafka offset, 如果是非COMMIT_OFFSET类型的ACK，为空串
     * </pre>
     *
     * <code>string offset = 3;</code>
     */
    public java.lang.String getOffset() {
      java.lang.Object ref = offset_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        offset_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * client已消费的kafka offset, 如果是非COMMIT_OFFSET类型的ACK，为空串
     * </pre>
     *
     * <code>string offset = 3;</code>
     */
    public com.google.protobuf.ByteString
        getOffsetBytes() {
      java.lang.Object ref = offset_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        offset_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int POSITION_FIELD_NUMBER = 4;
    private volatile java.lang.Object position_;
    /**
     * <pre>
     * client消费点的binlog位置
     * </pre>
     *
     * <code>string position = 4;</code>
     */
    public java.lang.String getPosition() {
      java.lang.Object ref = position_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        position_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * client消费点的binlog位置
     * </pre>
     *
     * <code>string position = 4;</code>
     */
    public com.google.protobuf.ByteString
        getPositionBytes() {
      java.lang.Object ref = position_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        position_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 5;
    private volatile java.lang.Object timestamp_;
    /**
     * <pre>
     * 最后一条binlog记录的时间戳
     * </pre>
     *
     * <code>string timestamp = 5;</code>
     */
    public java.lang.String getTimestamp() {
      java.lang.Object ref = timestamp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        timestamp_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 最后一条binlog记录的时间戳
     * </pre>
     *
     * <code>string timestamp = 5;</code>
     */
    public com.google.protobuf.ByteString
        getTimestampBytes() {
      java.lang.Object ref = timestamp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        timestamp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != com.bce.dts.protobuf.Common.MsgType.UNKNOW.getNumber()) {
        output.writeEnum(1, type_);
      }
      if (!getDtsIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, dtsId_);
      }
      if (!getOffsetBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, offset_);
      }
      if (!getPositionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, position_);
      }
      if (!getTimestampBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, timestamp_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != com.bce.dts.protobuf.Common.MsgType.UNKNOW.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (!getDtsIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, dtsId_);
      }
      if (!getOffsetBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, offset_);
      }
      if (!getPositionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, position_);
      }
      if (!getTimestampBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, timestamp_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.bce.dts.protobuf.EndOuterClass.End)) {
        return super.equals(obj);
      }
      com.bce.dts.protobuf.EndOuterClass.End other = (com.bce.dts.protobuf.EndOuterClass.End) obj;

      boolean result = true;
      result = result && type_ == other.type_;
      result = result && getDtsId()
          .equals(other.getDtsId());
      result = result && getOffset()
          .equals(other.getOffset());
      result = result && getPosition()
          .equals(other.getPosition());
      result = result && getTimestamp()
          .equals(other.getTimestamp());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + DTS_ID_FIELD_NUMBER;
      hash = (53 * hash) + getDtsId().hashCode();
      hash = (37 * hash) + OFFSET_FIELD_NUMBER;
      hash = (53 * hash) + getOffset().hashCode();
      hash = (37 * hash) + POSITION_FIELD_NUMBER;
      hash = (53 * hash) + getPosition().hashCode();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + getTimestamp().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.bce.dts.protobuf.EndOuterClass.End parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bce.dts.protobuf.EndOuterClass.End parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bce.dts.protobuf.EndOuterClass.End parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bce.dts.protobuf.EndOuterClass.End parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bce.dts.protobuf.EndOuterClass.End parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bce.dts.protobuf.EndOuterClass.End parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bce.dts.protobuf.EndOuterClass.End parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bce.dts.protobuf.EndOuterClass.End parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bce.dts.protobuf.EndOuterClass.End parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.bce.dts.protobuf.EndOuterClass.End parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bce.dts.protobuf.EndOuterClass.End parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bce.dts.protobuf.EndOuterClass.End parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.bce.dts.protobuf.EndOuterClass.End prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.bce.dts.protobuf.End}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.bce.dts.protobuf.End)
        com.bce.dts.protobuf.EndOuterClass.EndOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.bce.dts.protobuf.EndOuterClass.internal_static_baidu_river_End_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.bce.dts.protobuf.EndOuterClass.internal_static_baidu_river_End_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.bce.dts.protobuf.EndOuterClass.End.class, com.bce.dts.protobuf.EndOuterClass.End.Builder.class);
      }

      // Construct using com.bce.dts.protobuf.EndOuterClass.End.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        type_ = 0;

        dtsId_ = "";

        offset_ = "";

        position_ = "";

        timestamp_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bce.dts.protobuf.EndOuterClass.internal_static_baidu_river_End_descriptor;
      }

      public com.bce.dts.protobuf.EndOuterClass.End getDefaultInstanceForType() {
        return com.bce.dts.protobuf.EndOuterClass.End.getDefaultInstance();
      }

      public com.bce.dts.protobuf.EndOuterClass.End build() {
        com.bce.dts.protobuf.EndOuterClass.End result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.bce.dts.protobuf.EndOuterClass.End buildPartial() {
        com.bce.dts.protobuf.EndOuterClass.End result = new com.bce.dts.protobuf.EndOuterClass.End(this);
        result.type_ = type_;
        result.dtsId_ = dtsId_;
        result.offset_ = offset_;
        result.position_ = position_;
        result.timestamp_ = timestamp_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bce.dts.protobuf.EndOuterClass.End) {
          return mergeFrom((com.bce.dts.protobuf.EndOuterClass.End)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.bce.dts.protobuf.EndOuterClass.End other) {
        if (other == com.bce.dts.protobuf.EndOuterClass.End.getDefaultInstance()) return this;
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (!other.getDtsId().isEmpty()) {
          dtsId_ = other.dtsId_;
          onChanged();
        }
        if (!other.getOffset().isEmpty()) {
          offset_ = other.offset_;
          onChanged();
        }
        if (!other.getPosition().isEmpty()) {
          position_ = other.position_;
          onChanged();
        }
        if (!other.getTimestamp().isEmpty()) {
          timestamp_ = other.timestamp_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.bce.dts.protobuf.EndOuterClass.End parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.bce.dts.protobuf.EndOuterClass.End) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int type_ = 0;
      /**
       * <pre>
       * 消息类型
       * </pre>
       *
       * <code>.com.bce.dts.protobuf.MsgType type = 1;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <pre>
       * 消息类型
       * </pre>
       *
       * <code>.com.bce.dts.protobuf.MsgType type = 1;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息类型
       * </pre>
       *
       * <code>.com.bce.dts.protobuf.MsgType type = 1;</code>
       */
      public com.bce.dts.protobuf.Common.MsgType getType() {
        com.bce.dts.protobuf.Common.MsgType result = com.bce.dts.protobuf.Common.MsgType.valueOf(type_);
        return result == null ? com.bce.dts.protobuf.Common.MsgType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * 消息类型
       * </pre>
       *
       * <code>.com.bce.dts.protobuf.MsgType type = 1;</code>
       */
      public Builder setType(com.bce.dts.protobuf.Common.MsgType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息类型
       * </pre>
       *
       * <code>.com.bce.dts.protobuf.MsgType type = 1;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object dtsId_ = "";
      /**
       * <pre>
       * dts任务id
       * </pre>
       *
       * <code>string dts_id = 2;</code>
       */
      public java.lang.String getDtsId() {
        java.lang.Object ref = dtsId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          dtsId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * dts任务id
       * </pre>
       *
       * <code>string dts_id = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDtsIdBytes() {
        java.lang.Object ref = dtsId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dtsId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * dts任务id
       * </pre>
       *
       * <code>string dts_id = 2;</code>
       */
      public Builder setDtsId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        dtsId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * dts任务id
       * </pre>
       *
       * <code>string dts_id = 2;</code>
       */
      public Builder clearDtsId() {
        
        dtsId_ = getDefaultInstance().getDtsId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * dts任务id
       * </pre>
       *
       * <code>string dts_id = 2;</code>
       */
      public Builder setDtsIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        dtsId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object offset_ = "";
      /**
       * <pre>
       * client已消费的kafka offset, 如果是非COMMIT_OFFSET类型的ACK，为空串
       * </pre>
       *
       * <code>string offset = 3;</code>
       */
      public java.lang.String getOffset() {
        java.lang.Object ref = offset_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          offset_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * client已消费的kafka offset, 如果是非COMMIT_OFFSET类型的ACK，为空串
       * </pre>
       *
       * <code>string offset = 3;</code>
       */
      public com.google.protobuf.ByteString
          getOffsetBytes() {
        java.lang.Object ref = offset_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          offset_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * client已消费的kafka offset, 如果是非COMMIT_OFFSET类型的ACK，为空串
       * </pre>
       *
       * <code>string offset = 3;</code>
       */
      public Builder setOffset(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        offset_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * client已消费的kafka offset, 如果是非COMMIT_OFFSET类型的ACK，为空串
       * </pre>
       *
       * <code>string offset = 3;</code>
       */
      public Builder clearOffset() {
        
        offset_ = getDefaultInstance().getOffset();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * client已消费的kafka offset, 如果是非COMMIT_OFFSET类型的ACK，为空串
       * </pre>
       *
       * <code>string offset = 3;</code>
       */
      public Builder setOffsetBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        offset_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object position_ = "";
      /**
       * <pre>
       * client消费点的binlog位置
       * </pre>
       *
       * <code>string position = 4;</code>
       */
      public java.lang.String getPosition() {
        java.lang.Object ref = position_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          position_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * client消费点的binlog位置
       * </pre>
       *
       * <code>string position = 4;</code>
       */
      public com.google.protobuf.ByteString
          getPositionBytes() {
        java.lang.Object ref = position_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          position_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * client消费点的binlog位置
       * </pre>
       *
       * <code>string position = 4;</code>
       */
      public Builder setPosition(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        position_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * client消费点的binlog位置
       * </pre>
       *
       * <code>string position = 4;</code>
       */
      public Builder clearPosition() {
        
        position_ = getDefaultInstance().getPosition();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * client消费点的binlog位置
       * </pre>
       *
       * <code>string position = 4;</code>
       */
      public Builder setPositionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        position_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object timestamp_ = "";
      /**
       * <pre>
       * 最后一条binlog记录的时间戳
       * </pre>
       *
       * <code>string timestamp = 5;</code>
       */
      public java.lang.String getTimestamp() {
        java.lang.Object ref = timestamp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          timestamp_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 最后一条binlog记录的时间戳
       * </pre>
       *
       * <code>string timestamp = 5;</code>
       */
      public com.google.protobuf.ByteString
          getTimestampBytes() {
        java.lang.Object ref = timestamp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          timestamp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 最后一条binlog记录的时间戳
       * </pre>
       *
       * <code>string timestamp = 5;</code>
       */
      public Builder setTimestamp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 最后一条binlog记录的时间戳
       * </pre>
       *
       * <code>string timestamp = 5;</code>
       */
      public Builder clearTimestamp() {
        
        timestamp_ = getDefaultInstance().getTimestamp();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 最后一条binlog记录的时间戳
       * </pre>
       *
       * <code>string timestamp = 5;</code>
       */
      public Builder setTimestampBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        timestamp_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.bce.dts.protobuf.End)
    }

    // @@protoc_insertion_point(class_scope:com.bce.dts.protobuf.End)
    private static final com.bce.dts.protobuf.EndOuterClass.End DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.bce.dts.protobuf.EndOuterClass.End();
    }

    public static com.bce.dts.protobuf.EndOuterClass.End getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<End>
        PARSER = new com.google.protobuf.AbstractParser<End>() {
      public End parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new End(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<End> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<End> getParserForType() {
      return PARSER;
    }

    public com.bce.dts.protobuf.EndOuterClass.End getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_baidu_river_End_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_baidu_river_End_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tEnd.proto\022\013com.bce.dts.protobuf\032\014Common.proto\"n" +
      "\n\003End\022\"\n\004type\030\001 \001(\0162\024.com.bce.dts.protobuf.MsgTyp" +
      "e\022\016\n\006dts_id\030\002 \001(\t\022\016\n\006offset\030\003 \001(\t\022\020\n\010pos" +
      "ition\030\004 \001(\t\022\021\n\ttimestamp\030\005 \001(\tb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.bce.dts.protobuf.Common.getDescriptor(),
        }, assigner);
    internal_static_baidu_river_End_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_baidu_river_End_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_baidu_river_End_descriptor,
        new java.lang.String[] { "Type", "DtsId", "Offset", "Position", "Timestamp", });
    com.bce.dts.protobuf.Common.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
