// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Field.proto

package com.bce.dts.protobuf;

public final class FieldOuterClass {
  private FieldOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FieldOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.bce.dts.protobuf.Field)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 变更记录对应的字段名称
     * </pre>
     *
     * <code>string field_name = 1;</code>
     */
    java.lang.String getFieldName();
    /**
     * <pre>
     * 变更记录对应的字段名称
     * </pre>
     *
     * <code>string field_name = 1;</code>
     */
    com.google.protobuf.ByteString
        getFieldNameBytes();

    /**
     * <pre>
     * 变更记录对应的字段类型
     * </pre>
     *
     * <code>string field_type = 2;</code>
     */
    java.lang.String getFieldType();
    /**
     * <pre>
     * 变更记录对应的字段类型
     * </pre>
     *
     * <code>string field_type = 2;</code>
     */
    com.google.protobuf.ByteString
        getFieldTypeBytes();

    /**
     * <pre>
     * 变更记录对应的字段字符集编码，数值类型为空
     * </pre>
     *
     * <code>string field_charset = 3;</code>
     */
    java.lang.String getFieldCharset();
    /**
     * <pre>
     * 变更记录对应的字段字符集编码，数值类型为空
     * </pre>
     *
     * <code>string field_charset = 3;</code>
     */
    com.google.protobuf.ByteString
        getFieldCharsetBytes();

    /**
     * <pre>
     * 变更记录对应的字段修改前的值，对于insert操作，为空
     * </pre>
     *
     * <code>string value_before = 4;</code>
     */
    java.lang.String getValueBefore();
    /**
     * <pre>
     * 变更记录对应的字段修改前的值，对于insert操作，为空
     * </pre>
     *
     * <code>string value_before = 4;</code>
     */
    com.google.protobuf.ByteString
        getValueBeforeBytes();

    /**
     * <pre>
     * 变更记录对应的字段修改后的值，对于delete操作，为空
     * </pre>
     *
     * <code>string value_after = 5;</code>
     */
    java.lang.String getValueAfter();
    /**
     * <pre>
     * 变更记录对应的字段修改后的值，对于delete操作，为空
     * </pre>
     *
     * <code>string value_after = 5;</code>
     */
    com.google.protobuf.ByteString
        getValueAfterBytes();
  }
  /**
   * Protobuf type {@code com.bce.dts.protobuf.Field}
   */
  public  static final class Field extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.bce.dts.protobuf.Field)
      FieldOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Field.newBuilder() to construct.
    private Field(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Field() {
      fieldName_ = "";
      fieldType_ = "";
      fieldCharset_ = "";
      valueBefore_ = "";
      valueAfter_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Field(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              fieldName_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              fieldType_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              fieldCharset_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              valueBefore_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              valueAfter_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bce.dts.protobuf.FieldOuterClass.internal_static_baidu_river_Field_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bce.dts.protobuf.FieldOuterClass.internal_static_baidu_river_Field_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bce.dts.protobuf.FieldOuterClass.Field.class, com.bce.dts.protobuf.FieldOuterClass.Field.Builder.class);
    }

    public static final int FIELD_NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object fieldName_;
    /**
     * <pre>
     * 变更记录对应的字段名称
     * </pre>
     *
     * <code>string field_name = 1;</code>
     */
    public java.lang.String getFieldName() {
      java.lang.Object ref = fieldName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fieldName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 变更记录对应的字段名称
     * </pre>
     *
     * <code>string field_name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFieldNameBytes() {
      java.lang.Object ref = fieldName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fieldName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FIELD_TYPE_FIELD_NUMBER = 2;
    private volatile java.lang.Object fieldType_;
    /**
     * <pre>
     * 变更记录对应的字段类型
     * </pre>
     *
     * <code>string field_type = 2;</code>
     */
    public java.lang.String getFieldType() {
      java.lang.Object ref = fieldType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fieldType_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 变更记录对应的字段类型
     * </pre>
     *
     * <code>string field_type = 2;</code>
     */
    public com.google.protobuf.ByteString
        getFieldTypeBytes() {
      java.lang.Object ref = fieldType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fieldType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FIELD_CHARSET_FIELD_NUMBER = 3;
    private volatile java.lang.Object fieldCharset_;
    /**
     * <pre>
     * 变更记录对应的字段字符集编码，数值类型为空
     * </pre>
     *
     * <code>string field_charset = 3;</code>
     */
    public java.lang.String getFieldCharset() {
      java.lang.Object ref = fieldCharset_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fieldCharset_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 变更记录对应的字段字符集编码，数值类型为空
     * </pre>
     *
     * <code>string field_charset = 3;</code>
     */
    public com.google.protobuf.ByteString
        getFieldCharsetBytes() {
      java.lang.Object ref = fieldCharset_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fieldCharset_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VALUE_BEFORE_FIELD_NUMBER = 4;
    private volatile java.lang.Object valueBefore_;
    /**
     * <pre>
     * 变更记录对应的字段修改前的值，对于insert操作，为空
     * </pre>
     *
     * <code>string value_before = 4;</code>
     */
    public java.lang.String getValueBefore() {
      java.lang.Object ref = valueBefore_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        valueBefore_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 变更记录对应的字段修改前的值，对于insert操作，为空
     * </pre>
     *
     * <code>string value_before = 4;</code>
     */
    public com.google.protobuf.ByteString
        getValueBeforeBytes() {
      java.lang.Object ref = valueBefore_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        valueBefore_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VALUE_AFTER_FIELD_NUMBER = 5;
    private volatile java.lang.Object valueAfter_;
    /**
     * <pre>
     * 变更记录对应的字段修改后的值，对于delete操作，为空
     * </pre>
     *
     * <code>string value_after = 5;</code>
     */
    public java.lang.String getValueAfter() {
      java.lang.Object ref = valueAfter_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        valueAfter_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 变更记录对应的字段修改后的值，对于delete操作，为空
     * </pre>
     *
     * <code>string value_after = 5;</code>
     */
    public com.google.protobuf.ByteString
        getValueAfterBytes() {
      java.lang.Object ref = valueAfter_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        valueAfter_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getFieldNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, fieldName_);
      }
      if (!getFieldTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, fieldType_);
      }
      if (!getFieldCharsetBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, fieldCharset_);
      }
      if (!getValueBeforeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, valueBefore_);
      }
      if (!getValueAfterBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, valueAfter_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getFieldNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, fieldName_);
      }
      if (!getFieldTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, fieldType_);
      }
      if (!getFieldCharsetBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, fieldCharset_);
      }
      if (!getValueBeforeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, valueBefore_);
      }
      if (!getValueAfterBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, valueAfter_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.bce.dts.protobuf.FieldOuterClass.Field)) {
        return super.equals(obj);
      }
      com.bce.dts.protobuf.FieldOuterClass.Field other = (com.bce.dts.protobuf.FieldOuterClass.Field) obj;

      boolean result = true;
      result = result && getFieldName()
          .equals(other.getFieldName());
      result = result && getFieldType()
          .equals(other.getFieldType());
      result = result && getFieldCharset()
          .equals(other.getFieldCharset());
      result = result && getValueBefore()
          .equals(other.getValueBefore());
      result = result && getValueAfter()
          .equals(other.getValueAfter());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FIELD_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getFieldName().hashCode();
      hash = (37 * hash) + FIELD_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getFieldType().hashCode();
      hash = (37 * hash) + FIELD_CHARSET_FIELD_NUMBER;
      hash = (53 * hash) + getFieldCharset().hashCode();
      hash = (37 * hash) + VALUE_BEFORE_FIELD_NUMBER;
      hash = (53 * hash) + getValueBefore().hashCode();
      hash = (37 * hash) + VALUE_AFTER_FIELD_NUMBER;
      hash = (53 * hash) + getValueAfter().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.bce.dts.protobuf.FieldOuterClass.Field parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bce.dts.protobuf.FieldOuterClass.Field parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bce.dts.protobuf.FieldOuterClass.Field parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bce.dts.protobuf.FieldOuterClass.Field parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bce.dts.protobuf.FieldOuterClass.Field parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bce.dts.protobuf.FieldOuterClass.Field parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bce.dts.protobuf.FieldOuterClass.Field parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bce.dts.protobuf.FieldOuterClass.Field parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bce.dts.protobuf.FieldOuterClass.Field parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.bce.dts.protobuf.FieldOuterClass.Field parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bce.dts.protobuf.FieldOuterClass.Field parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bce.dts.protobuf.FieldOuterClass.Field parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.bce.dts.protobuf.FieldOuterClass.Field prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.bce.dts.protobuf.Field}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.bce.dts.protobuf.Field)
        com.bce.dts.protobuf.FieldOuterClass.FieldOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.bce.dts.protobuf.FieldOuterClass.internal_static_baidu_river_Field_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.bce.dts.protobuf.FieldOuterClass.internal_static_baidu_river_Field_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.bce.dts.protobuf.FieldOuterClass.Field.class, com.bce.dts.protobuf.FieldOuterClass.Field.Builder.class);
      }

      // Construct using com.bce.dts.protobuf.FieldOuterClass.Field.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        fieldName_ = "";

        fieldType_ = "";

        fieldCharset_ = "";

        valueBefore_ = "";

        valueAfter_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bce.dts.protobuf.FieldOuterClass.internal_static_baidu_river_Field_descriptor;
      }

      public com.bce.dts.protobuf.FieldOuterClass.Field getDefaultInstanceForType() {
        return com.bce.dts.protobuf.FieldOuterClass.Field.getDefaultInstance();
      }

      public com.bce.dts.protobuf.FieldOuterClass.Field build() {
        com.bce.dts.protobuf.FieldOuterClass.Field result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.bce.dts.protobuf.FieldOuterClass.Field buildPartial() {
        com.bce.dts.protobuf.FieldOuterClass.Field result = new com.bce.dts.protobuf.FieldOuterClass.Field(this);
        result.fieldName_ = fieldName_;
        result.fieldType_ = fieldType_;
        result.fieldCharset_ = fieldCharset_;
        result.valueBefore_ = valueBefore_;
        result.valueAfter_ = valueAfter_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bce.dts.protobuf.FieldOuterClass.Field) {
          return mergeFrom((com.bce.dts.protobuf.FieldOuterClass.Field)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.bce.dts.protobuf.FieldOuterClass.Field other) {
        if (other == com.bce.dts.protobuf.FieldOuterClass.Field.getDefaultInstance()) return this;
        if (!other.getFieldName().isEmpty()) {
          fieldName_ = other.fieldName_;
          onChanged();
        }
        if (!other.getFieldType().isEmpty()) {
          fieldType_ = other.fieldType_;
          onChanged();
        }
        if (!other.getFieldCharset().isEmpty()) {
          fieldCharset_ = other.fieldCharset_;
          onChanged();
        }
        if (!other.getValueBefore().isEmpty()) {
          valueBefore_ = other.valueBefore_;
          onChanged();
        }
        if (!other.getValueAfter().isEmpty()) {
          valueAfter_ = other.valueAfter_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.bce.dts.protobuf.FieldOuterClass.Field parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.bce.dts.protobuf.FieldOuterClass.Field) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object fieldName_ = "";
      /**
       * <pre>
       * 变更记录对应的字段名称
       * </pre>
       *
       * <code>string field_name = 1;</code>
       */
      public java.lang.String getFieldName() {
        java.lang.Object ref = fieldName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          fieldName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 变更记录对应的字段名称
       * </pre>
       *
       * <code>string field_name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getFieldNameBytes() {
        java.lang.Object ref = fieldName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fieldName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 变更记录对应的字段名称
       * </pre>
       *
       * <code>string field_name = 1;</code>
       */
      public Builder setFieldName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        fieldName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 变更记录对应的字段名称
       * </pre>
       *
       * <code>string field_name = 1;</code>
       */
      public Builder clearFieldName() {
        
        fieldName_ = getDefaultInstance().getFieldName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 变更记录对应的字段名称
       * </pre>
       *
       * <code>string field_name = 1;</code>
       */
      public Builder setFieldNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        fieldName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object fieldType_ = "";
      /**
       * <pre>
       * 变更记录对应的字段类型
       * </pre>
       *
       * <code>string field_type = 2;</code>
       */
      public java.lang.String getFieldType() {
        java.lang.Object ref = fieldType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          fieldType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 变更记录对应的字段类型
       * </pre>
       *
       * <code>string field_type = 2;</code>
       */
      public com.google.protobuf.ByteString
          getFieldTypeBytes() {
        java.lang.Object ref = fieldType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fieldType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 变更记录对应的字段类型
       * </pre>
       *
       * <code>string field_type = 2;</code>
       */
      public Builder setFieldType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        fieldType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 变更记录对应的字段类型
       * </pre>
       *
       * <code>string field_type = 2;</code>
       */
      public Builder clearFieldType() {
        
        fieldType_ = getDefaultInstance().getFieldType();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 变更记录对应的字段类型
       * </pre>
       *
       * <code>string field_type = 2;</code>
       */
      public Builder setFieldTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        fieldType_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object fieldCharset_ = "";
      /**
       * <pre>
       * 变更记录对应的字段字符集编码，数值类型为空
       * </pre>
       *
       * <code>string field_charset = 3;</code>
       */
      public java.lang.String getFieldCharset() {
        java.lang.Object ref = fieldCharset_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          fieldCharset_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 变更记录对应的字段字符集编码，数值类型为空
       * </pre>
       *
       * <code>string field_charset = 3;</code>
       */
      public com.google.protobuf.ByteString
          getFieldCharsetBytes() {
        java.lang.Object ref = fieldCharset_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fieldCharset_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 变更记录对应的字段字符集编码，数值类型为空
       * </pre>
       *
       * <code>string field_charset = 3;</code>
       */
      public Builder setFieldCharset(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        fieldCharset_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 变更记录对应的字段字符集编码，数值类型为空
       * </pre>
       *
       * <code>string field_charset = 3;</code>
       */
      public Builder clearFieldCharset() {
        
        fieldCharset_ = getDefaultInstance().getFieldCharset();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 变更记录对应的字段字符集编码，数值类型为空
       * </pre>
       *
       * <code>string field_charset = 3;</code>
       */
      public Builder setFieldCharsetBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        fieldCharset_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object valueBefore_ = "";
      /**
       * <pre>
       * 变更记录对应的字段修改前的值，对于insert操作，为空
       * </pre>
       *
       * <code>string value_before = 4;</code>
       */
      public java.lang.String getValueBefore() {
        java.lang.Object ref = valueBefore_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          valueBefore_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 变更记录对应的字段修改前的值，对于insert操作，为空
       * </pre>
       *
       * <code>string value_before = 4;</code>
       */
      public com.google.protobuf.ByteString
          getValueBeforeBytes() {
        java.lang.Object ref = valueBefore_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          valueBefore_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 变更记录对应的字段修改前的值，对于insert操作，为空
       * </pre>
       *
       * <code>string value_before = 4;</code>
       */
      public Builder setValueBefore(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        valueBefore_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 变更记录对应的字段修改前的值，对于insert操作，为空
       * </pre>
       *
       * <code>string value_before = 4;</code>
       */
      public Builder clearValueBefore() {
        
        valueBefore_ = getDefaultInstance().getValueBefore();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 变更记录对应的字段修改前的值，对于insert操作，为空
       * </pre>
       *
       * <code>string value_before = 4;</code>
       */
      public Builder setValueBeforeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        valueBefore_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object valueAfter_ = "";
      /**
       * <pre>
       * 变更记录对应的字段修改后的值，对于delete操作，为空
       * </pre>
       *
       * <code>string value_after = 5;</code>
       */
      public java.lang.String getValueAfter() {
        java.lang.Object ref = valueAfter_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          valueAfter_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 变更记录对应的字段修改后的值，对于delete操作，为空
       * </pre>
       *
       * <code>string value_after = 5;</code>
       */
      public com.google.protobuf.ByteString
          getValueAfterBytes() {
        java.lang.Object ref = valueAfter_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          valueAfter_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 变更记录对应的字段修改后的值，对于delete操作，为空
       * </pre>
       *
       * <code>string value_after = 5;</code>
       */
      public Builder setValueAfter(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        valueAfter_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 变更记录对应的字段修改后的值，对于delete操作，为空
       * </pre>
       *
       * <code>string value_after = 5;</code>
       */
      public Builder clearValueAfter() {
        
        valueAfter_ = getDefaultInstance().getValueAfter();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 变更记录对应的字段修改后的值，对于delete操作，为空
       * </pre>
       *
       * <code>string value_after = 5;</code>
       */
      public Builder setValueAfterBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        valueAfter_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.bce.dts.protobuf.Field)
    }

    // @@protoc_insertion_point(class_scope:com.bce.dts.protobuf.Field)
    private static final com.bce.dts.protobuf.FieldOuterClass.Field DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.bce.dts.protobuf.FieldOuterClass.Field();
    }

    public static com.bce.dts.protobuf.FieldOuterClass.Field getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Field>
        PARSER = new com.google.protobuf.AbstractParser<Field>() {
      public Field parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Field(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Field> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Field> getParserForType() {
      return PARSER;
    }

    public com.bce.dts.protobuf.FieldOuterClass.Field getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_baidu_river_Field_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_baidu_river_Field_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Field.proto\022\013com.bce.dts.protobuf\"q\n\005Field\022\022\n\nf" +
      "ield_name\030\001 \001(\t\022\022\n\nfield_type\030\002 \001(\t\022\025\n\rf" +
      "ield_charset\030\003 \001(\t\022\024\n\014value_before\030\004 \001(\t" +
      "\022\023\n\013value_after\030\005 \001(\tb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_baidu_river_Field_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_baidu_river_Field_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_baidu_river_Field_descriptor,
        new java.lang.String[] { "FieldName", "FieldType", "FieldCharset", "ValueBefore", "ValueAfter", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
