// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msgType.proto

package com.bce.dts.protobuf;

public final class MsgTypeProto {
    private MsgTypeProto() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    /**
     * Protobuf enum {@code protobuf.MsgType}
     */
    public enum MsgType
            implements com.google.protobuf.ProtocolMessageEnum {
        /**
         * <code>AUTH = 0;</code>
         */
        AUTH(0),
        /**
         * <code>EVENT = 1;</code>
         */
        EVENT(1),
        /**
         * <code>ACK = 2;</code>
         */
        ACK(2),
        UNRECOGNIZED(-1),
        ;

        /**
         * <code>AUTH = 0;</code>
         */
        public static final int AUTH_VALUE = 0;
        /**
         * <code>EVENT = 1;</code>
         */
        public static final int EVENT_VALUE = 1;
        /**
         * <code>ACK = 2;</code>
         */
        public static final int ACK_VALUE = 2;

        public final int getNumber() {
            if (this == UNRECOGNIZED) {
                throw new java.lang.IllegalArgumentException(
                        "Can't get the number of an unknown enum value.");
            }
            return value;
        }

        /**
         * @deprecated Use {@link #forNumber(int)} instead.
         */
        @java.lang.Deprecated
        public static MsgType valueOf(int value) {
            return forNumber(value);
        }

        public static MsgType forNumber(int value) {
            switch (value) {
                case 0:
                    return AUTH;
                case 1:
                    return EVENT;
                case 2:
                    return ACK;
                default:
                    return null;
            }
        }

        public static com.google.protobuf.Internal.EnumLiteMap<MsgType> internalGetValueMap() {
            return internalValueMap;
        }

        private static final com.google.protobuf.Internal.EnumLiteMap<MsgType> internalValueMap =
                new com.google.protobuf.Internal.EnumLiteMap<MsgType>() {
                    public MsgType findValueByNumber(int number) {
                        return MsgType.forNumber(number);
                    }
                };

        public final com.google.protobuf.Descriptors.EnumValueDescriptor getValueDescriptor() {
            return getDescriptor().getValues().get(ordinal());
        }

        public final com.google.protobuf.Descriptors.EnumDescriptor getDescriptorForType() {
            return getDescriptor();
        }

        public static final com.google.protobuf.Descriptors.EnumDescriptor getDescriptor() {
            return com.bce.dts.protobuf.MsgTypeProto.getDescriptor().getEnumTypes().get(0);
        }

        private static final MsgType[] VALUES = values();

        public static MsgType valueOf(
                com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
            if (desc.getType() != getDescriptor()) {
                throw new java.lang.IllegalArgumentException(
                        "EnumValueDescriptor is not for this type.");
            }
            if (desc.getIndex() == -1) {
                return UNRECOGNIZED;
            }
            return VALUES[desc.getIndex()];
        }

        private final int value;

        private MsgType(int value) {
            this.value = value;
        }

        // @@protoc_insertion_point(enum_scope:protobuf.MsgType)
    }

    public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
    static {
        java.lang.String[] descriptorData = {
                "\n\rmsgType.proto\022\010protobuf*\'\n\007MsgType\022\010\n\004" +
                        "AUTH\020\000\022\t\n\005EVENT\020\001\022\007\n\003ACK\020\002B$\n\024com.bce.dt" +
                        "s.protobufB\014MsgTypeProtob\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[] {
                        }, assigner);
    }

    // @@protoc_insertion_point(outer_class_scope)
}
